routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/recipient', 'RecipientController');
Route::resource('/product', 'ProductController');
Route::resource('/transaction', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Transaction;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class TransactionController extends Controller
{
/**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Transaction::with(['village', 'product']);
            return DataTables::of($data)
                ->addColumn('action', function ($data) {
                    return view('layouts.partials._action', [
                        'model' => $data,
                        'show_url' => route('transaction.show', $data->id),
                        'edit_url' => route('transaction.edit', $data->id),
                        'delete_url' => route('transaction.destroy', $data->id)
                    ]);
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        return view('pages.transaction.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = Product::pluck('name', 'id');
        return view('pages.transaction.create', compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // return $request->all();

        $this->validate($request, [
            'village_id' => 'required',
            'product_id' => 'required',
            'qty_sold' => 'required',
            'qty_stock' => 'required',
        ]);

        $product = Product::findOrFail($request->product_id);

        $data = [
            'date' => $request->date,
            'village_id' => $request->village_id,
            'product_id' => $request->product_id,
            'unit' => $product->unit,
            'price_basic' => $product->price_basic,
            'price_sell' => $product->price_sell,
            'qty_sold' => $request->qty_sold,
            'qty_stock' =>  $request->qty_stock,
            'total_sell' => $request->qty_sold * $product->price_sell,
            'total_stock' => $request->qty_stock * $product->price_sell,
        ];

        Transaction::create($data);

        return redirect()->route('transaction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Transaction::findOrFail($id);
        return view('pages.transaction.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Transaction::findOrFail($id);
        $product = Product::pluck('name', 'id');
        return view('pages.transaction.edit', compact('data', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $transaction = Transaction::findOrFail($id);

        $this->validate($request, [
            'village_id' => 'required',
            'product_id' => 'required',
            'qty_sold' => 'required',
            'qty_stock' => 'required',
        ]);

        $product = Product::findOrFail($request->product_id);

        $data = [
            'date' => $request->date,
            'village_id' => $request->village_id,
            'product_id' => $request->product_id,
            'unit' => $product->unit,
            'price_basic' => $product->price_basic,
            'price_sell' => $product->price_sell,
            'qty_sold' => $request->qty_sold,
            'qty_stock' =>  $request->qty_stock,
            'total_sell' => $request->qty_sold * $product->price_sell,
            'total_stock' => $request->qty_stock * $product->price_sell,
        ];

        $transaction->update($data);

        return redirect()->route('transaction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $transaction = Transaction::findOrFail($id);
        $transaction->delete();

        return redirect()->route('transaction.index');
    }
}

resources/views/pages/transaction/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Penerima</a></li>
                        <li class="breadcrumb-item active">Tambah</li>
                    </ol>
                </div>
                <h4 class="page-title">Tambah</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

     <!-- Form row -->
     <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Form Input</h4>
                    <form action="{{ route('transaction.store') }}" method="POST">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="" class="col-form-label">Tanggal</label>
                                <input type="date" name="date" id="" class="form-control">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Desa</label>
                                <select name="village_id" id="" class="form-control search" data-toggle="select2">
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Produk</label>
                                <select name="product_id" id="" class="form-control">
                                    @foreach ($product as $key => $value)
                                        <option value="{{ $key }}">{{ $value }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Qty Jual</label>
                                <input type="number" name="qty_sold" class="form-control" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Sisa Stock</label>
                                <input type="number" name="qty_stock" class="form-control" required>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>

                    </form>
                </div> <!-- end card-body -->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
    <!-- end row -->

</div> <!-- container -->
@endsection

@push('styles')
<link href="{{ asset('assets/libs/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css"/>
@endpush

@push('scripts')
<script src="{{ asset('assets/libs/select2/js/select2.min.js') }}"></script>
<script type="text/javascript">
  $('.search').select2({
    placeholder: 'Cari...',
    ajax: {
      url: '/api/village',
      dataType: 'json',
      delay: 250,
      processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.title,
              id: item.id
            }
          })
        };
      },
      cache: true
    }
  });
</script>
@endpush

resources/views/pages/transaction/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Penerima</a></li>
                        <li class="breadcrumb-item active">Tambah</li>
                    </ol>
                </div>
                <h4 class="page-title">Tambah</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

     <!-- Form row -->
     <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Form Input</h4>
                    <form action="{{ route('transaction.update', $data->id) }}" method="POST">
                        @csrf @method('PUT')

                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="" class="col-form-label">Tanggal</label>
                                <input type="date" name="date" id="" class="form-control" value="{{ $data->date }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Desa</label>
                                <select name="village_id" id="" class="form-control search" data-toggle="select2">
                                    <option value="{{ $data->village_id }}" selected>{{ $data->village->title }}</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Produk</label>
                                <select name="product_id" id="" class="form-control">
                                    @foreach ($product as $key => $value)
                                        <option value="{{ $key }}" {{ $data->product_id == $key ? 'selected' : ''}}>{{ $value }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Qty Jual</label>
                                <input type="number" name="qty_sold" class="form-control" value="{{ $data->qty_sold }}" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Sisa Stock</label>
                                <input type="number" name="qty_stock" class="form-control" value="{{ $data->qty_stock }}" required>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>

                    </form>
                </div> <!-- end card-body -->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
    <!-- end row -->

</div> <!-- container -->
@endsection


@push('styles')
<link href="{{ asset('assets/libs/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css"/>
@endpush

@push('scripts')
<script src="{{ asset('assets/libs/select2/js/select2.min.js') }}"></script>
<script type="text/javascript">
  $('.search').select2({
    placeholder: 'Cari...',
    ajax: {
      url: '/api/village',
      dataType: 'json',
      delay: 250,
      processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.title,
              id: item.id
            }
          })
        };
      },
      cache: true
    }
  });
</script>
@endpush

resources/views/pages/transaction/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Transaksi</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-4">
                            <a href="{{ route('transaction.create') }}" class="btn btn-danger mb-2"><i class="mdi mdi-plus-circle mr-2"></i> Tambah</a>
                        </div>
                        <div class="col-sm-8">
                            <div class="text-sm-right">
                                <button type="button" class="btn btn-success mb-2 mr-1"><i class="mdi mdi-cog"></i></button>
                                <button type="button" class="btn btn-light mb-2">Export</button>
                            </div>
                        </div><!-- end col-->
                    </div>

                    <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Desa</th>
                                <th>Produk</th>
                                <th>Jml Jual</th>
                                <th>Total</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->


</div> <!-- container -->
@endsection

@push('styles')
    <!-- third party css -->
    <link href="{{ asset('/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- third party css end -->
@endpush

@push('scripts')
    <!-- third party js -->
    <script src="{{ asset('/assets/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
    <!-- third party js ends -->

    <script>
        $(document).ready(function () {
            $("#basic-datatable").DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('transaction.index') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'id'},
                    {data: 'village.title', name: 'village.title'},
                    {data: 'product.name', name: 'product.name'},
                    {data: 'qty_sold', name: 'qty_sold'},
                    {data: 'total_sell', name: 'total_sell', "render": function(data) {
                        return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' }).format(data)
                    }},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                language: {
                    paginate: {
                        previous: "<i class='mdi mdi-chevron-left'>",
                        next: "<i class='mdi mdi-chevron-right'>"
                    }
                },
                drawCallback: function () {
                    $(".dataTables_paginate > .pagination").addClass("pagination-rounded")
                }
            });
        });
    </script>
@endpush

resources/views/pages/transaction/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Penerima</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <h5 class="card-header">Details</h5>
                <div class="card-body">
                    <table class="table mb-0">
                        <tbody>
                        <tr>
                            <th scope="row" class="bg-secondary text-white" width="20%">
                                Nama
                            </th>
                            <td>{{ $recipient->name }}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="bg-secondary text-white">
                                Persentase
                            </th>
                            <td>
                                {{ $recipient->percentage }}%
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="bg-secondary text-white">
                                Status
                            </th>
                            <td>{{ $recipient->is_active ? 'Aktif' : 'Non-aktif' }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- end col-->
    </div>
    <!-- end row-->


</div> <!-- container -->
@endsection