routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/recipient', 'RecipientController');
Route::resource('/product', 'ProductController');
Route::resource('/transaction', 'TransactionController');

app/Recipient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipient extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/RecipientController.php
<?php

namespace App\Http\Controllers;

use App\Recipient;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class RecipientController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Recipient::query();
            return DataTables::of($data)
                ->addColumn('action', function ($data) {
                    return view('layouts.partials._action', [
                        'model' => $data,
                        'show_url' => route('recipient.show', $data->id),
                        'edit_url' => route('recipient.edit', $data->id),
                        'delete_url' => route('recipient.destroy', $data->id)
                    ]);
                })
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        return view('pages.recipient.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.recipient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'percentage' => 'numeric',
            'is_active' => 'boolean'
        ]);

        Recipient::create($request->all());

        return redirect()->route('recipient.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $recipient = Recipient::findOrFail($id);
        return view('pages.recipient.show', compact('recipient'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Recipient::findOrFail($id);
        return view('pages.recipient.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $recipient = Recipient::findOrFail($id);

        $data = $this->validate($request, [
            'name' => 'required|string',
            'percentage' => 'numeric',
            'is_active' => 'boolean'
        ]);

        $recipient->update($data);

        return redirect()->route('recipient.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $recipient = Recipient::findOrFail($id);
        $recipient->delete();

        return redirect()->route('recipient.index');
    }
}

resources/views/pages/recipient/create.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Penerima</a></li>
                        <li class="breadcrumb-item active">Tambah</li>
                    </ol>
                </div>
                <h4 class="page-title">Tambah</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

     <!-- Form row -->
     <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Form Input</h4>
                    <form action="{{ route('recipient.store') }}" method="POST">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Nama</label>
                                <input type="text" name="name" class="form-control" placeholder="Nama">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Persentase</label>
                                <input type="number" name="percentage" class="form-control" placeholder="Persentase">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="col-form-label">Status Aktif</label>
                            <div class="radio radio-primary">
                                <input type="radio" name="is_active" id="radio1" value="1" checked>
                                <label for="radio1">
                                    Aktif
                                </label>
                            </div>
                            <div class="radio radio-primary">
                                <input type="radio" name="is_active" id="radio2" value="0">
                                <label for="radio2">
                                    Non-aktif
                                </label>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>

                    </form>
                </div> <!-- end card-body -->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
    <!-- end row -->

</div> <!-- container -->
@endsection

resources/views/pages/recipient/edit.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Penerima</a></li>
                        <li class="breadcrumb-item active">Tambah</li>
                    </ol>
                </div>
                <h4 class="page-title">Tambah</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

     <!-- Form row -->
     <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Form Input</h4>
                    <form action="{{ route('recipient.update', $data->id) }}" method="POST">
                        @csrf @method('PUT')
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Nama</label>
                                <input type="text" name="name" class="form-control" placeholder="Nama" value="{{ $data->name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="" class="col-form-label">Persentase</label>
                                <input type="number" name="percentage" class="form-control" placeholder="Persentase" value="{{ $data->percentage }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="" class="col-form-label">Status Aktif</label>
                            <div class="radio radio-primary">
                                <input type="radio" name="is_active" id="radio1" value="1" {{ $data->is_active == '1' ? 'checked' : '' }}>
                                <label for="radio1">
                                    Aktif
                                </label>
                            </div>
                            <div class="radio radio-primary">
                                <input type="radio" name="is_active" id="radio2" value="0" {{ $data->is_active == '0' ? 'checked' : '' }}>
                                <label for="radio2">
                                    Non-aktif
                                </label>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>

                    </form>
                </div> <!-- end card-body -->
            </div> <!-- end card-->
        </div> <!-- end col -->
    </div>
    <!-- end row -->

</div> <!-- container -->
@endsection

resources/views/pages/recipient/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Penerima</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-sm-4">
                            <a href="{{ route('recipient.create') }}" class="btn btn-danger mb-2"><i class="mdi mdi-plus-circle mr-2"></i> Tambah</a>
                        </div>
                        <div class="col-sm-8">
                            <div class="text-sm-right">
                                <button type="button" class="btn btn-success mb-2 mr-1"><i class="mdi mdi-cog"></i></button>
                                <button type="button" class="btn btn-light mb-2">Export</button>
                            </div>
                        </div><!-- end col-->
                    </div>

                    <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Penerima</th>
                                <th>Persentase (%)</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->


</div> <!-- container -->
@endsection

@push('styles')
    <!-- third party css -->
    <link href="{{ asset('/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}" rel="stylesheet" type="text/css" />
    <!-- third party css end -->
@endpush

@push('scripts')
    <!-- third party js -->
    <script src="{{ asset('/assets/libs/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('/assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
    <!-- third party js ends -->

    <script>
        $(document).ready(function () {
            $("#basic-datatable").DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('recipient.index') }}",
                columns: [
                    {data: 'DT_RowIndex', name: 'id'},
                    {data: 'name', name: 'name'},
                    {data: 'percentage', name: 'percentage', "render": function(data) {
                        return `${data}%`
                    }},
                    {data: 'is_active', name: 'is_active', "render": function(data) {
                        return data ? 'Aktif' : 'Non-aktif'
                    }},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                language: {
                    paginate: {
                        previous: "<i class='mdi mdi-chevron-left'>",
                        next: "<i class='mdi mdi-chevron-right'>"
                    }
                },
                drawCallback: function () {
                    $(".dataTables_paginate > .pagination").addClass("pagination-rounded")
                }
            });
        });
    </script>
@endpush

resources/views/pages/recipient/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Start Content-->
<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">Penerima</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <h5 class="card-header">Details</h5>
                <div class="card-body">
                    <table class="table mb-0">
                        <tbody>
                        <tr>
                            <th scope="row" class="bg-secondary text-white" width="20%">
                                Nama
                            </th>
                            <td>{{ $recipient->name }}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="bg-secondary text-white">
                                Persentase
                            </th>
                            <td>
                                {{ $recipient->percentage }}%
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="bg-secondary text-white">
                                Status
                            </th>
                            <td>{{ $recipient->is_active ? 'Aktif' : 'Non-aktif' }}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- end col-->
    </div>
    <!-- end row-->


</div> <!-- container -->
@endsection